INFO 2025-04-14 20:31:06,893 autoreload Watching for file changes with StatReloader
INFO 2025-04-14 20:31:13,553 basehttp "GET / HTTP/1.1" 200 5377
WARNING 2025-04-14 20:31:14,599 log Not Found: /favicon.ico
WARNING 2025-04-14 20:31:14,600 basehttp "GET /favicon.ico HTTP/1.1" 404 3165
INFO 2025-04-14 20:31:57,252 autoreload Watching for file changes with StatReloader
INFO 2025-04-14 20:32:00,509 basehttp "GET / HTTP/1.1" 200 5377
INFO 2025-04-14 20:33:47,949 autoreload Watching for file changes with StatReloader
INFO 2025-04-14 20:33:50,704 basehttp "GET / HTTP/1.1" 200 5377
INFO 2025-04-14 20:35:39,153 basehttp "POST / HTTP/1.1" 200 5785
INFO 2025-04-14 20:36:09,263 basehttp "POST / HTTP/1.1" 200 5785
INFO 2025-04-14 20:36:43,201 basehttp "POST / HTTP/1.1" 200 5785
INFO 2025-04-14 20:42:53,465 autoreload Watching for file changes with StatReloader
INFO 2025-04-14 20:43:01,060 basehttp "POST / HTTP/1.1" 200 5785
INFO 2025-04-14 21:11:58,545 basehttp "POST / HTTP/1.1" 200 5650
INFO 2025-04-14 21:13:38,328 basehttp "POST / HTTP/1.1" 200 5830
INFO 2025-04-14 21:15:42,440 basehttp "POST / HTTP/1.1" 200 5830
INFO 2025-04-14 21:17:04,961 basehttp "POST / HTTP/1.1" 200 5830
INFO 2025-04-14 21:28:21,582 basehttp "POST / HTTP/1.1" 200 6015
ERROR 2025-04-14 21:28:30,018 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lucian/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lucian/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "/home/lucian/.local/lib/python3.10/site-packages/django/contrib/sessions/middleware.py", line 59, in process_response
    request.session.save()
  File "/home/lucian/.local/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 121, in save
    return self.create()
  File "/home/lucian/.local/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 70, in create
    self._session_key = self._get_new_session_key()
  File "/home/lucian/.local/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 196, in _get_new_session_key
    if not self.exists(session_key):
  File "/home/lucian/.local/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 63, in exists
    return self.model.objects.filter(session_key=session_key).exists()
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/home/lucian/.local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: django_session
ERROR 2025-04-14 21:28:30,027 basehttp "POST / HTTP/1.1" 500 144682
INFO 2025-04-14 22:38:02,327 autoreload Watching for file changes with StatReloader
INFO 2025-04-14 22:38:07,576 basehttp "GET / HTTP/1.1" 200 5607
INFO 2025-04-14 22:38:14,321 basehttp "POST / HTTP/1.1" 200 5933
INFO 2025-04-21 21:21:55,745 autoreload Watching for file changes with StatReloader
INFO 2025-04-21 21:22:04,989 basehttp "GET / HTTP/1.1" 200 5607
WARNING 2025-04-21 21:22:06,212 log Not Found: /favicon.ico
WARNING 2025-04-21 21:22:06,213 basehttp "GET /favicon.ico HTTP/1.1" 404 3165
INFO 2025-04-21 21:22:22,973 basehttp "POST / HTTP/1.1" 200 5933
INFO 2025-04-21 21:22:35,184 basehttp "POST /enhance/ HTTP/1.1" 200 13338
ERROR 2025-04-21 21:22:48,367 basehttp "GET /download/?format=docx HTTP/1.1" 500 59
ERROR 2025-04-21 21:23:57,666 basehttp "GET /download/?format=docx HTTP/1.1" 500 59
ERROR 2025-04-21 21:24:01,271 basehttp "GET /download/?format=pdf HTTP/1.1" 500 59
INFO 2025-04-21 22:45:56,505 autoreload Watching for file changes with StatReloader
INFO 2025-04-21 22:46:00,171 basehttp "GET / HTTP/1.1" 200 5607
INFO 2025-04-21 22:46:07,132 basehttp "POST / HTTP/1.1" 200 5933
INFO 2025-04-21 22:46:15,294 basehttp "POST /enhance/ HTTP/1.1" 200 13104
INFO 2025-04-21 22:46:17,911 basehttp "GET /download/?format=docx HTTP/1.1" 200 37748
INFO 2025-04-21 23:02:37,798 autoreload Watching for file changes with StatReloader
INFO 2025-04-21 23:02:40,964 basehttp "GET / HTTP/1.1" 200 5607
INFO 2025-04-21 23:04:24,775 autoreload Watching for file changes with StatReloader
INFO 2025-04-21 23:04:27,119 basehttp "GET / HTTP/1.1" 200 5607
INFO 2025-04-21 23:07:11,159 basehttp "POST / HTTP/1.1" 200 6013
INFO 2025-04-21 23:07:23,650 basehttp "GET / HTTP/1.1" 200 5607
